DATA:
  IMG_SIZE: 224
  DATA_PATH: "/home/ssd_14T/caogp/public_data/CIFAR10"
  DATASET: CIFAR10
MODEL:
  TYPE: strip_mlp_layer
  NAME: smlp_tiny_alpha3_patch4_224_cifa10_G4
  DROP: False
  DROP_RATE: 0.2
  NUM_CLASSES: 10
  ALPHA: 3
  PATCH_NORM: True
  STRIP_MLP:
    EMBED_DIM: 80
    LAYERS: [2, 2, 12, 2]